<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1.1 (Python 3.7.6 on win32)" generated="20210331 22:29:52.700" rpa="false">
<suite id="s1" name="DataDrivenTest" source="C:\Users\fitim\IdeaProjects\PythonProject\PythonProject\testcases\DataDrivenTest.robot">
<kw name="Open my Browser" type="setup">
<kw name="Open Browser">
<arguments>
<arg>http://demoaut.katalon.com/</arg>
<arg>headlesschrome</arg>
</arguments>
<msg timestamp="20210331 22:29:54.911" level="FAIL">No keyword with name 'Open Browser' found. Did you mean:
    Open My Browser</msg>
<status status="FAIL" starttime="20210331 22:29:54.910" endtime="20210331 22:29:54.911"></status>
</kw>
<status status="FAIL" starttime="20210331 22:29:54.904" endtime="20210331 22:29:54.912"></status>
</kw>
<test id="s1-t1" name="Login to Application">
<status status="FAIL" starttime="20210331 22:29:54.913" endtime="20210331 22:29:54.915" critical="yes">Parent suite setup failed:
No keyword with name 'Open Browser' found. Did you mean:
    Open My Browser</status>
</test>
<kw name="Close Browsers" type="teardown">
<kw name="Close All Browsers">
<msg timestamp="20210331 22:29:54.923" level="FAIL">No keyword with name 'Close All Browsers' found. Did you mean:
    Close Browsers</msg>
<status status="FAIL" starttime="20210331 22:29:54.922" endtime="20210331 22:29:54.924"></status>
</kw>
<status status="FAIL" starttime="20210331 22:29:54.916" endtime="20210331 22:29:54.925">No keyword with name 'Close All Browsers' found. Did you mean:
    Close Browsers</status>
</kw>
<status status="FAIL" starttime="20210331 22:29:52.710" endtime="20210331 22:29:54.926">Suite setup failed:
No keyword with name 'Open Browser' found. Did you mean:
    Open My Browser

Also suite teardown failed:
No keyword with name 'Close All Browsers' found. Did you mean:
    Close Browsers</status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="DataDrivenTest">DataDrivenTest</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210331 22:29:54.895" level="ERROR">Error in file 'C:\Users\fitim\IdeaProjects\PythonProject\PythonProject\testcases\DataDrivenTest.robot': Initializing test library 'SeleniumLibrary' with no arguments failed: TypeError: replace_string() got an unexpected keyword argument 'custom_unescaper'
Traceback (most recent call last):
  File "c:\Users\fitim\.vscode\extensions\jacobphilip.danfoss-robotframework-debug-1.4.2\out\RobotFrameworkDebugHelpers\robotf\running\testlibraries.py", line 167, in _get_instance
    return libcode(*self.positional_args, **dict(self.named_args))
  File "C:\Users\fitim\AppData\Local\Programs\Python\Python37\lib\site-packages\SeleniumLibrary\__init__.py", line 464, in __init__
    BrowserManagementKeywords(self),
  File "C:\Users\fitim\AppData\Local\Programs\Python\Python37\lib\site-packages\SeleniumLibrary\keywords\browsermanagement.py", line 37, in __init__
    self._webdriver_creator = WebDriverCreator(self.log_dir)
  File "C:\Users\fitim\AppData\Local\Programs\Python\Python37\lib\site-packages\SeleniumLibrary\base\librarycomponent.py", line 86, in log_dir
    logfile = BuiltIn().get_variable_value("${LOG FILE}")
  File "C:\Users\fitim\AppData\Local\Programs\Python\Python37\lib\site-packages\robot\libraries\BuiltIn.py", line 1443, in get_variable_value
    name = self._get_var_name(name)
  File "C:\Users\fitim\AppData\Local\Programs\Python\Python37\lib\site-packages\robot\libraries\BuiltIn.py", line 1716, in _get_var_name
    match.resolve_base(self._variables)
  File "C:\Users\fitim\AppData\Local\Programs\Python\Python37\lib\site-packages\robot\variables\search.py", line 91, in resolve_base
    ignore_errors=ignore_errors,</msg>
<msg timestamp="20210331 22:29:54.902" level="ERROR">Calling method '_start_suite' of listener 'DataDriver' failed: TypeError: replace_string() got an unexpected keyword argument 'custom_unescaper'</msg>
</errors>
</robot>
